Repository m-lab/annotation-service, pull requests merged in 2018-12, with the labels that each got.

#126 Code cleanup
  .travis.yml
  annotator.sh
  api/api.go
  geolite2/g2_test.go
  geolite2/geo-g2.go
  geolite2/geo-ip.go
  geolite2/geo-ip_test.go
  handler/handler.go
  handler/handler_test.go
  legacy/geoip.go
  legacy/legacy-dataset.go
  legacy/legacy-dataset_test.go
  manager/manager.go
  metrics/metrics.go
Labels: 1, P2, Sprint 22, Story

#128 There are now zero (0) lint errors!
  geolite2/g2_test.go
  handler/handler.go
  handler/handler_test.go
  legacy/const.go
  legacy/geoip.go
  legacy/legacy-dataset.go
  legacy/legacy-dataset_test.go
  legacy/testdata/geoip-demo.go
  loader/loader.go
  manager/manager.go
Labels: 1, P1, Sprint 22

#133 Fix prom lint
  metrics/metrics.go
  metrics/metrics_test.go
Labels: 1, P1, Sprint 22

#159 Add target for cron.yaml
  cron.yaml
Labels: Sprint 23
